version: '3'
services:
  cockroachdb:
    container_name: cockroachdb
    image: cockroachdb/cockroach:v19.2.2
    command: start --insecure --store=attrs=ssd,path=/var/lib/cockroach/
    restart: always
    volumes:
      - /opt/cockroach:/var/lib/cockroach
    expose:
      - "8080"
      - "26257"
    ports:
      - "26257:26257"
      - "8080:8080"
  nakama:
    container_name: nakama
    image: heroiclabs/nakama:2.9.1
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
          /nakama/nakama migrate up --database.address root@cockroachdb:26257 &&
          exec /nakama/nakama --config "/nakama/config/config.yml"
          # exec /nakama/nakama --name nakama_papua --socket.server_key "nakama_papua" --database.address root@cockroachdb:26257
    restart: always
    links:
      - "cockroachdb"
    depends_on:
      - cockroachdb
    volumes:
      - /opt/nakama/data:/nakama/data
      - /opt/nakama/logs:/nakama/logs
      - ./config:/nakama/config
      - ./modules/logs:/nakama/modules
    expose:
      - "7349"
      - "7350"
      - "7351"
      - "7353"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
      - "7353:7353"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7350/"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  data:
